name: GPT researcher integration workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Targeted branch'
        required: true
        default: 'ailab-main'

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.head_ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/ai-cfia
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/ai-cfia/gpt-researcher:latest

      - name: Build & Push frontend (prod) image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/nextjs
          file: ./frontend/nextjs/Dockerfile
          push: true
          tags: ghcr.io/ai-cfia/gpt-researcher-frontend-prod:latest
      
      - name: Build & Push frontend (dev) image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/nextjs
          file: ./frontend/nextjs/Dockerfile.dev
          push: true
          tags: ghcr.io/ai-cfia/gpt-researcher-frontend-dev:latest
